package com.stride.android;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import com.stride.android.databinding.ActivityMainBinding;
import org.json.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Native client for every workspace area provided by the original Stride web app. */
public class MainActivity extends Activity {
    private static final int PRIMARY = Color.rgb(91, 92, 226), INK = Color.rgb(29,27,32), MUTED = Color.rgb(98,99,112);
    private LinearLayout content; private SharedPreferences prefs; private SupabaseApi api;
    private FrameLayout screenRoot, drawer; private ActivityMainBinding mainBinding; private String activePage = "Overview";
    private JSONObject user; private CountDownTimer timer; private long timeLeft;
    private final String[] pages = {"Overview", "Notes", "Calendar", "Tasks", "Goals", "Focus", "Settings", "Logout"};

    @Override public void onCreate(Bundle state) { super.onCreate(state); prefs=getSharedPreferences("stride",MODE_PRIVATE); api=new SupabaseApi(); timeLeft=prefs.getLong("focus_time",25*60_000L); restoreSession(); }
    @Override protected void onPause() { super.onPause(); prefs.edit().putLong("focus_time",timeLeft).apply(); }
    @Override public void onBackPressed() { if(drawer!=null&&drawer.getVisibility()==View.VISIBLE){closeDrawer();return;} if(user!=null&&!activePage.equals("Overview")){showDashboard();return;} super.onBackPressed(); }

    private void restoreSession() {
        String email=prefs.getString("userEmail",""); if(email.isEmpty()) { showLogin(); return; }
        api.get("users", SupabaseApi.and("select=*",SupabaseApi.eq("email",email)), (rows,error)-> { if(error!=null||rows.length()!=1) { signOut(); } else { user=rows.optJSONObject(0); showDashboard(); } });
    }
    private void shell(String title, FeatureScreen screen) {
        LinearLayout root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(Color.rgb(248,248,252));
        LinearLayout bar=new LinearLayout(this); bar.setGravity(Gravity.CENTER_VERTICAL); bar.setPadding(dp(8),dp(10),dp(10),dp(10)); bar.setBackgroundColor(PRIMARY);
        boolean canGoBack=!activePage.equals("Overview");
        if(canGoBack){ Button back=iconButton("‹"); back.setContentDescription("Back"); back.setOnClickListener(v->showDashboard()); bar.addView(back,new LinearLayout.LayoutParams(dp(48),dp(52))); }
        TextView brand=text(canGoBack?title:"✦  Stride.",canGoBack?20:24,Color.WHITE); brand.setTypeface(null,Typeface.BOLD); bar.addView(brand,new LinearLayout.LayoutParams(0,dp(52),1));
        Button menu=iconButton("☰"); menu.setContentDescription("Open navigation menu"); menu.setOnClickListener(v->openDrawer()); bar.addView(menu,new LinearLayout.LayoutParams(dp(54),dp(52))); root.addView(bar);
        content=screen.content(); content.setPadding(dp(18),dp(18),dp(18),dp(30)); root.addView(screen.root(),new LinearLayout.LayoutParams(-1,0,1));
        mainBinding=ActivityMainBinding.inflate(getLayoutInflater()); setContentView(mainBinding.getRoot()); screenRoot=mainBinding.screenRoot; screenRoot.addView(root); buildDrawer();
        TextView heading=text(title,27,INK); heading.setTypeface(null,Typeface.BOLD); content.addView(heading); spacer(5);
    }
    private void buildDrawer(){
        drawer=new FrameLayout(this); drawer.setVisibility(View.GONE); drawer.setBackgroundColor(0x66000000); drawer.setClickable(true); drawer.setOnClickListener(v->closeDrawer()); screenRoot.addView(drawer,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout panel=new LinearLayout(this); panel.setOrientation(LinearLayout.VERTICAL); panel.setPadding(dp(20),dp(28),dp(16),dp(20)); panel.setBackgroundColor(Color.WHITE); panel.setElevation(dp(12)); panel.setClickable(true); drawer.addView(panel,new FrameLayout.LayoutParams(dp(310),-1,Gravity.START));
        TextView logo=text("✦  Stride.",28,PRIMARY); logo.setTypeface(null,Typeface.BOLD); panel.addView(logo); spacer(panel,6);
        TextView identity=text(user==null?"Your focused workspace":user.optString("full_name","Your workspace")+"\n"+user.optString("email"),14,MUTED); identity.setLineSpacing(dp(2),1f); panel.addView(identity); spacer(panel,24);
        String[] labels={"Overview","Notes","Calendar","Tasks","Goals","Focus","Settings"}; String[] icons={"⌂","✎","□","✓","◎","◷","⚙"};
        for(int i=0;i<labels.length;i++){ final int index=i; Button item=drawerItem(icons[i]+"   "+labels[i],labels[i].equals(activePage)); item.setOnClickListener(v->{closeDrawer();navigateTo(index);}); panel.addView(item); spacer(panel,3); }
        Space fill=new Space(this); panel.addView(fill,new LinearLayout.LayoutParams(1,0,1));
        Button logout=drawerItem("⇥   Log out",false); logout.setTextColor(Color.rgb(184,55,75)); logout.setOnClickListener(v->{closeDrawer();signOut();}); panel.addView(logout);
    }
    private void openDrawer(){if(drawer!=null){drawer.setVisibility(View.VISIBLE);}}
    private void closeDrawer(){if(drawer!=null)drawer.setVisibility(View.GONE);}
    private void navigateTo(int i){ switch(i) { case 0:showDashboard();break;case 1:showNotes();break;case 2:showCalendar();break;case 3:showTasks();break;case 4:showGoals();break;case 5:showFocus();break;case 6:showProfile();break; }}
    private boolean loggedIn() { if(user==null){showLogin();return false;} return true; }

    // Authentication mirrors the web app's manual users-table flow.
    private void showLogin() {
        LoginScreen screen=new LoginScreen(getLayoutInflater()); setContentView(screen.binding.getRoot()); EditText email=screen.email(); EditText password=screen.password(); Button signIn=screen.signIn(); Button create=screen.createAccount();
        signIn.setOnClickListener(v->{ String e=email.getText().toString().trim(), p=password.getText().toString(); if(e.isEmpty()||p.isEmpty()){toast("Enter your email and password");return;} signIn.setEnabled(false); api.get("users",SupabaseApi.and("select=*",SupabaseApi.eq("email",e),SupabaseApi.eq("password",p)),(rows,error)->{signIn.setEnabled(true);if(error!=null||rows.length()!=1){toast("Invalid email or password");}else{user=rows.optJSONObject(0);prefs.edit().putString("userEmail",e).apply();showDashboard();}}); });
        create.setOnClickListener(v->showSignup());
    }
    private void showSignup() {
        SignupScreen screen=new SignupScreen(getLayoutInflater()); setContentView(screen.binding.getRoot()); EditText name=screen.name(), email=screen.email(), pass=screen.password(), confirm=screen.confirmPassword(); Button create=screen.createAccount(), back=screen.backToSignIn();
        create.setOnClickListener(v->{String n=name.getText().toString().trim(),e=email.getText().toString().trim(),p=pass.getText().toString();if(n.isEmpty()||e.isEmpty()||p.isEmpty()){toast("Complete every field");return;}if(!p.equals(confirm.getText().toString())){toast("Passwords don't match");return;} JSONObject body=new JSONObject();try{body.put("id",UUID.randomUUID().toString());body.put("full_name",n);body.put("email",e);body.put("password",p);}catch(Exception ignored){} create.setEnabled(false);api.insert("users",body,(rows,error)->{create.setEnabled(true);if(error!=null)toast(error.contains("23505")?"Email already exists": "Could not create account");else{toast("Account created. Please sign in.");showLogin();}});}); back.setOnClickListener(v->showLogin());
    }
    private void signOut() { if(timer!=null)timer.cancel(); timer=null; user=null; prefs.edit().remove("userEmail").apply(); showLogin(); }

    private void showDashboard() { if(!loggedIn())return; activePage="Overview"; shell("Welcome back, " + first(user.optString("full_name","there")) + "!",new DashboardScreen(getLayoutInflater())); content.addView(text("Here's what's happening in your workspace today.",16,MUTED));spacer(18); String enabled=user.optString("features",""); addDash("📝  Notes","Write and organize your thoughts.",v->showNotes(), enabled.isEmpty()||enabled.contains("Notes")); addDash("📅  Calendar","Schedule focused work and personal events.",v->showCalendar(),enabled.isEmpty()||enabled.contains("Calendar"));addDash("✅  Tasks","Keep track of your to-dos.",v->showTasks(),enabled.isEmpty()||enabled.contains("Todo"));addDash("🎯  Goals","Set and achieve your milestones.",v->showGoals(),enabled.isEmpty()||enabled.contains("Goals"));addDash("⏱️  Focus","Master productivity with a timer.",v->showFocus(),true); }
    private void addDash(String title,String sub,View.OnClickListener listener,boolean visible){if(!visible)return;card(title,sub,"Open",listener);spacer(12);}

    private void showTasks() { if(!loggedIn())return; activePage="Tasks"; shell("Tasks",new TasksScreen(getLayoutInflater())); content.addView(text("Manage your to-dos and track your momentum.",16,MUTED));spacer(14);Button add=button("+ New task",true);content.addView(add);spacer(16); LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);loadTasks(list,"all");add.setOnClickListener(v->taskDialog(null,list)); }
    private void loadTasks(LinearLayout list,String filter){ list.removeAllViews(); api.get("tasks",SupabaseApi.and("select=*",SupabaseApi.eq("user_id",user.optString("id")),"order=created_at.desc"),(rows,error)->{if(error!=null){list.addView(text("Could not load tasks.",16,MUTED));return;}if(rows.length()==0)list.addView(text("No tasks yet.",16,MUTED));for(int i=0;i<rows.length();i++){JSONObject task=rows.optJSONObject(i); if(!filter.equals("all")&&!filter.equals(task.optString("status")))continue; entityRow(list,task,task.optString("title"),task.optString("priority","Medium")+" · "+task.optString("status","todo")+(task.optString("due_date").isEmpty()?"":" · "+task.optString("due_date")),v->taskActions(task,list));}}); }
    private void taskDialog(JSONObject existing,LinearLayout list){
        LinearLayout f=dialogForm(); EditText title=field("What needs to be done?",1),details=field("Details (optional)",1),due=field("Due date (YYYY-MM-DD)",1),priority=field("Priority: Low, Medium, or High",1); if(existing!=null){title.setText(existing.optString("title"));details.setText(existing.optString("details"));due.setText(existing.optString("due_date"));priority.setText(existing.optString("priority","Medium"));} else priority.setText("Medium"); f.addView(title);f.addView(details);f.addView(due);f.addView(priority);
        AlertDialog d=new AlertDialog.Builder(this).setTitle(existing==null?"New task":"Edit task").setView(f).setNegativeButton("Cancel",null).setPositiveButton(existing==null?"Create":"Update",null).create(); d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(title.getText().toString().trim().isEmpty())return;JSONObject b=obj("user_id",user.optString("id"),"title",title.getText().toString().trim(),"details",emptyNull(details),"due_date",emptyNull(due),"priority",priority.getText().toString().trim(),"updated_at",now()); SupabaseApi.Callback done=(r,e)->{if(e!=null)toast("Could not save task");else{d.dismiss();loadTasks(list,"all");}};if(existing==null)api.insert("tasks",obj("user_id",user.optString("id"),"title",title.getText().toString().trim(),"details",emptyNull(details),"due_date",emptyNull(due),"priority",priority.getText().toString().trim(),"status","todo","updated_at",now()),done);else api.update("tasks",SupabaseApi.eq("id",existing.optString("id")),b,done);}));d.show();
    }
    private void taskActions(JSONObject task,LinearLayout list){ String[] choices={"Mark To Do","Mark Active","Mark Done","Edit","Delete"}; new AlertDialog.Builder(this).setTitle(task.optString("title")).setItems(choices,(d,w)->{if(w<3){api.update("tasks",SupabaseApi.eq("id",task.optString("id")),obj("status",new String[]{"todo","doing","done"}[w],"updated_at",now()),(r,e)->loadTasks(list,"all"));}else if(w==3)taskDialog(task,list);else confirmDelete("task",task,"tasks",list,l->loadTasks(l,"all"));}).show(); }

    private void showNotes(){if(!loggedIn())return;activePage="Notes";shell("Notes",new NotesScreen(getLayoutInflater()));content.addView(text("Capture and organize your thoughts.",16,MUTED));spacer(12);Button add=button("+ New note",true);content.addView(add);spacer(14);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);loadNotes(list);add.setOnClickListener(v->noteEditor(null,list));}
    private void loadNotes(LinearLayout list){list.removeAllViews();api.get("notes",SupabaseApi.and("select=*",SupabaseApi.eq("user_id",user.optString("id")),"order=updated_at.desc"),(rows,e)->{if(e!=null){list.addView(text("Could not load notes.",16,MUTED));return;}if(rows.length()==0)list.addView(text("No notes yet.",16,MUTED));for(int i=0;i<rows.length();i++){JSONObject note=rows.optJSONObject(i);entityRow(list,note,note.optString("title","Untitled Note"),strip(note.optString("content")),v->noteEditor(note,list));}});}
    private void noteEditor(JSONObject existing,LinearLayout list){LinearLayout f=dialogForm();EditText title=field("Title",1),body=field("Write something worth remembering…",1);body.setMinLines(7);body.setGravity(Gravity.TOP);if(existing!=null){title.setText(existing.optString("title"));body.setText(existing.optString("content"));}f.addView(title);f.addView(body);AlertDialog d=new AlertDialog.Builder(this).setTitle(existing==null?"New note":"Edit note").setView(f).setNegativeButton("Cancel",null).setNeutralButton(existing==null?"":"Delete",null).setPositiveButton("Save",null).create();d.setOnShowListener(x->{d.getButton(-1).setOnClickListener(v->{JSONObject b=obj("user_id",user.optString("id"),"title",title.getText().toString().trim().isEmpty()?"Untitled Note":title.getText().toString().trim(),"content",body.getText().toString(),"updated_at",now());SupabaseApi.Callback cb=(r,e)->{if(e!=null)toast("Could not save note");else{d.dismiss();loadNotes(list);}};if(existing==null)api.insert("notes",b,cb);else api.update("notes",SupabaseApi.eq("id",existing.optString("id")),b,cb);});if(existing!=null)d.getButton(-3).setOnClickListener(v->confirmDelete("note",existing,"notes",list,this::loadNotes));});d.show();}

    private void showGoals(){if(!loggedIn())return;activePage="Goals";shell("Goals",new GoalsScreen(getLayoutInflater()));content.addView(text("Set milestones and track your momentum.",16,MUTED));spacer(12);Button add=button("+ New goal",true);content.addView(add);spacer(14);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);loadGoals(list);add.setOnClickListener(v->goalDialog(null,list));}
    private void loadGoals(LinearLayout list){list.removeAllViews();api.get("goals",SupabaseApi.and("select=*",SupabaseApi.eq("user_id",user.optString("id")),"order=created_at.desc"),(rows,e)->{if(e!=null){list.addView(text("Could not load goals.",16,MUTED));return;}if(rows.length()==0)list.addView(text("No goals yet.",16,MUTED));for(int i=0;i<rows.length();i++){JSONObject g=rows.optJSONObject(i);double t=g.optDouble("target_value",100),c=g.optDouble("current_value",0);entityRow(list,g,g.optString("title"),String.format(Locale.US,"%.0f / %.0f %s",c,t,g.optString("unit","%")),v->goalActions(g,list));}});}
    private void goalDialog(JSONObject existing,LinearLayout list){LinearLayout f=dialogForm();EditText title=field("Goal title",1),notes=field("Notes",1),target=field("Target value",2),current=field("Current value",2),unit=field("Unit (%, pages, sessions)",1),date=field("Target date (YYYY-MM-DD)",1);if(existing!=null){title.setText(existing.optString("title"));notes.setText(existing.optString("notes"));target.setText(existing.optString("target_value","100"));current.setText(existing.optString("current_value","0"));unit.setText(existing.optString("unit","%"));date.setText(existing.optString("target_date"));}else{target.setText("100");current.setText("0");unit.setText("%");}for(EditText x:new EditText[]{title,notes,target,current,unit,date})f.addView(x);AlertDialog d=new AlertDialog.Builder(this).setTitle(existing==null?"New goal":"Edit goal").setView(f).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(title.getText().toString().trim().isEmpty())return;JSONObject b=obj("user_id",user.optString("id"),"title",title.getText().toString().trim(),"notes",emptyNull(notes),"target_value",number(target,100),"current_value",number(current,0),"unit",unit.getText().toString().trim(),"target_date",emptyNull(date),"updated_at",now());SupabaseApi.Callback cb=(r,e)->{if(e!=null)toast("Could not save goal");else{d.dismiss();loadGoals(list);}};if(existing==null)api.insert("goals",b,cb);else api.update("goals",SupabaseApi.eq("id",existing.optString("id")),b,cb);}));d.show();}
    private void goalActions(JSONObject goal,LinearLayout list){new AlertDialog.Builder(this).setTitle(goal.optString("title")).setItems(new String[]{"Update progress","Edit","Delete"},(d,w)->{if(w==0){EditText value=field("Current value",2);value.setText(goal.optString("current_value"));new AlertDialog.Builder(this).setTitle("Update progress").setView(value).setPositiveButton("Save",(a,b)->api.update("goals",SupabaseApi.eq("id",goal.optString("id")),obj("current_value",number(value,0),"updated_at",now()),(r,e)->loadGoals(list))).setNegativeButton("Cancel",null).show();}else if(w==1)goalDialog(goal,list);else confirmDelete("goal",goal,"goals",list,this::loadGoals);}).show();}

    private void showCalendar(){if(!loggedIn())return;activePage="Calendar";shell("Smart Calendar",new CalendarScreen(getLayoutInflater()));content.addView(text("Plan focused work, deadlines, and personal events.",16,MUTED));spacer(12);EditText date=field("Date (YYYY-MM-DD)",1);date.setText(today());content.addView(date);spacer(8);Button add=button("+ Schedule event",true);content.addView(add);spacer(14);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);content.addView(list);loadEvents(list,date.getText().toString());date.setOnFocusChangeListener((v,has)->{if(!has)loadEvents(list,date.getText().toString());});add.setOnClickListener(v->eventDialog(null,list,date.getText().toString()));}
    private void loadEvents(LinearLayout list,String date){list.removeAllViews();api.get("calendar_events",SupabaseApi.and("select=*",SupabaseApi.eq("user_id",user.optString("id")),SupabaseApi.eq("event_date",date),"order=start_time.asc"),(rows,e)->{if(e!=null){list.addView(text("Could not load events.",16,MUTED));return;}if(rows.length()==0)list.addView(text("Free day!",16,MUTED));for(int i=0;i<rows.length();i++){JSONObject event=rows.optJSONObject(i);entityRow(list,event,event.optString("title"),event.optString("category","Focus")+" · "+event.optString("start_time","Any time"),v->eventActions(event,list,date));}});}
    private void eventDialog(JSONObject existing,LinearLayout list,String selectedDate){LinearLayout f=dialogForm();EditText title=field("Event title",1),details=field("Details",1),date=field("Date (YYYY-MM-DD)",1),start=field("Start time (HH:MM)",1),end=field("End time (HH:MM)",1),category=field("Category: Focus, Meeting, Personal, Deadline",1);date.setText(selectedDate);category.setText("Focus");if(existing!=null){title.setText(existing.optString("title"));details.setText(existing.optString("details"));date.setText(existing.optString("event_date"));start.setText(existing.optString("start_time"));end.setText(existing.optString("end_time"));category.setText(existing.optString("category","Focus"));}for(EditText x:new EditText[]{title,details,date,start,end,category})f.addView(x);AlertDialog d=new AlertDialog.Builder(this).setTitle(existing==null?"Schedule event":"Edit event").setView(f).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(title.getText().toString().trim().isEmpty()||date.getText().toString().trim().isEmpty())return;JSONObject b=obj("user_id",user.optString("id"),"title",title.getText().toString().trim(),"details",emptyNull(details),"event_date",date.getText().toString().trim(),"start_time",emptyNull(start),"end_time",emptyNull(end),"category",category.getText().toString().trim(),"updated_at",now());SupabaseApi.Callback cb=(r,e)->{if(e!=null)toast("Could not save event");else{d.dismiss();loadEvents(list,date.getText().toString());}};if(existing==null)api.insert("calendar_events",b,cb);else api.update("calendar_events",SupabaseApi.eq("id",existing.optString("id")),b,cb);}));d.show();}
    private void eventActions(JSONObject event,LinearLayout list,String date){new AlertDialog.Builder(this).setTitle(event.optString("title")).setItems(new String[]{"Edit","Delete"},(d,w)->{if(w==0)eventDialog(event,list,date);else confirmDelete("event",event,"calendar_events",list,(l)->loadEvents(l,date));}).show();}

    private void showFocus(){if(!loggedIn())return;activePage="Focus";shell("Focus",new FocusScreen(getLayoutInflater()));content.addView(text("Choose a technique and protect your attention.",16,MUTED));spacer(16);TextView countdown=text(format(timeLeft),52,PRIMARY);countdown.setGravity(Gravity.CENTER);countdown.setTypeface(null,Typeface.BOLD);content.addView(countdown,new LinearLayout.LayoutParams(-1,dp(100)));TextView label=text(prefs.getString("focus_tech","Pomodoro")+" · "+prefs.getString("focus_mode","Work"),16,MUTED);label.setGravity(Gravity.CENTER);content.addView(label);spacer(14);LinearLayout controls=new LinearLayout(this);Button start=button(timer==null?"Start":"Pause",true),reset=button("Reset",false);controls.addView(start,new LinearLayout.LayoutParams(0,dp(52),1));controls.addView(reset,new LinearLayout.LayoutParams(0,dp(52),1));content.addView(controls);spacer(12);Button modes=button("Change mode / technique",false);content.addView(modes);start.setOnClickListener(v->{if(timer!=null){timer.cancel();timer=null;start.setText("Resume");return;}start.setText("Pause");timer=new CountDownTimer(timeLeft,1000){public void onTick(long ms){timeLeft=ms;countdown.setText(format(ms));}public void onFinish(){timeLeft=0;timer=null;start.setText("Start again");countdown.setText("Done!");prefs.edit().putInt("focus_sessions",prefs.getInt("focus_sessions",0)+1).apply();}}.start();});reset.setOnClickListener(v->{if(timer!=null)timer.cancel();timer=null;timeLeft=duration();countdown.setText(format(timeLeft));start.setText("Start");});modes.setOnClickListener(v->focusOptions(label,countdown,start));}
    private void focusOptions(TextView label,TextView countdown,Button start){new AlertDialog.Builder(this).setTitle("Focus technique").setItems(new String[]{"Pomodoro (25/5/15)","52/17 rule", "Flowtime (90/10/25)"},(d,w)->{String[] names={"Pomodoro","52/17 rule","Flowtime"};prefs.edit().putString("focus_tech",names[w]).putString("focus_mode","Work").apply();timeLeft=duration();label.setText(names[w]+" · Work");countdown.setText(format(timeLeft));start.setText("Start");}).show();}
    private long duration(){String t=prefs.getString("focus_tech","Pomodoro");return (t.equals("52/17 rule")?52:t.equals("Flowtime")?90:25)*60_000L;}

    private void showProfile(){if(!loggedIn())return;activePage="Settings";shell("Profile & settings",new SettingsScreen(getLayoutInflater()));content.addView(text(user.optString("email"),16,MUTED));spacer(16);Button edit=button("Edit profile",true),features=button("Choose dashboard features",false),logout=button("Logout",false);content.addView(edit);spacer(8);content.addView(features);spacer(8);content.addView(logout);edit.setOnClickListener(v->{LinearLayout f=dialogForm();EditText name=field("Full name",1),email=field("Email",1);name.setText(user.optString("full_name"));email.setText(user.optString("email"));f.addView(name);f.addView(email);new AlertDialog.Builder(this).setTitle("Edit profile").setView(f).setPositiveButton("Save",(d,w)->api.update("users",SupabaseApi.eq("id",user.optString("id")),obj("full_name",name.getText().toString().trim(),"email",email.getText().toString().trim()),(r,e)->{if(e==null){user=obj("full_name",name.getText().toString().trim(),"email",email.getText().toString().trim(),"id",user.optString("id"),"features",user.opt("features"));prefs.edit().putString("userEmail",email.getText().toString().trim()).apply();showProfile();}else toast("Could not save profile");})).setNegativeButton("Cancel",null).show();});features.setOnClickListener(v->featureDialog());logout.setOnClickListener(v->signOut());}
    private void featureDialog(){String[] names={"Notes","Calendar","Todo","Goals"};boolean[] selected=new boolean[4];String values=user.optString("features","");for(int i=0;i<4;i++)selected[i]=values.isEmpty()||values.contains(names[i]);new AlertDialog.Builder(this).setTitle("Dashboard features").setMultiChoiceItems(names,selected,(d,w,on)->selected[w]=on).setPositiveButton("Save",(d,w)->{JSONArray a=new JSONArray();for(int i=0;i<4;i++)if(selected[i])a.put(names[i]);api.update("users",SupabaseApi.eq("id",user.optString("id")),obj("features",a),(r,e)->{if(e==null){user=obj("id",user.optString("id"),"full_name",user.optString("full_name"),"email",user.optString("email"),"features",a);toast("Features updated");}else toast("Could not update features");});}).setNegativeButton("Cancel",null).show();}

    private interface ListLoader { void load(LinearLayout list); }
    private void confirmDelete(String label,JSONObject item,String table,LinearLayout list,ListLoader reload){new AlertDialog.Builder(this).setTitle("Delete "+label+"?").setMessage("This cannot be undone.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->api.delete(table,SupabaseApi.eq("id",item.optString("id")),(r,e)->{if(e!=null)toast("Could not delete "+label);else reload.load(list);})).show();}
    private LinearLayout formPage(String heading,String description){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(28),dp(56),dp(28),dp(28));TextView h=text("✦  Stride.\n"+heading,29,PRIMARY);h.setTypeface(null,Typeface.BOLD);box.addView(h);spacer(box,12);box.addView(text(description,16,MUTED));spacer(box,30);return box;}
    private View wrap(View child){ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(Color.rgb(248,248,252));scroll.addView(child);return scroll;}
    private LinearLayout dialogForm(){LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(18),dp(6),dp(18),0);return form;}
    private EditText field(String hint,int type){EditText input=new EditText(this);input.setHint(hint);input.setTextSize(16);input.setTextColor(INK);input.setInputType(type);input.setPadding(dp(12),dp(10),dp(12),dp(10));input.setBackground(round(Color.WHITE,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(8));input.setLayoutParams(lp);return input;}
    private void entityRow(LinearLayout parent,JSONObject item,String title,String subtitle,View.OnClickListener click){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(16),dp(13),dp(16),dp(13));row.setBackground(round(Color.WHITE,16));row.setOnClickListener(click);TextView t=text(title,18,INK);t.setTypeface(null,Typeface.BOLD);row.addView(t);if(!subtitle.isEmpty()){spacer(row,4);row.addView(text(subtitle,14,MUTED));}parent.addView(row);spacer(parent,9);}
    private void card(String title,String body,String action,View.OnClickListener listener){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(17),dp(16),dp(17),dp(16));box.setBackground(round(Color.WHITE,18));TextView h=text(title,19,INK);h.setTypeface(null,Typeface.BOLD);box.addView(h);spacer(box,6);box.addView(text(body,15,MUTED));spacer(box,12);Button b=button(action,true);b.setOnClickListener(listener);box.addView(b);content.addView(box);}
    private Button button(String label,boolean filled){Button b=new Button(this);b.setText(label);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(filled?Color.WHITE:PRIMARY);b.setBackground(round(filled?PRIMARY:Color.WHITE,13));return b;}
    private Button iconButton(String label){Button b=new Button(this);b.setText(label);b.setTextSize(29);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setPadding(0,0,0,dp(3));b.setBackgroundColor(Color.TRANSPARENT);return b;}
    private Button drawerItem(String label,boolean selected){Button b=new Button(this);b.setText(label);b.setTextSize(16);b.setGravity(Gravity.CENTER_VERTICAL|Gravity.START);b.setAllCaps(false);b.setPadding(dp(14),0,dp(10),0);b.setTextColor(selected?PRIMARY:INK);b.setTypeface(null,selected?Typeface.BOLD:Typeface.NORMAL);b.setBackground(round(selected?Color.rgb(238,238,255):Color.WHITE,12));return b;}
    private TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);return t;}
    private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private void spacer(int value){spacer(content,value);} private void spacer(LinearLayout p,int value){Space s=new Space(this);p.addView(s,new LinearLayout.LayoutParams(1,dp(value)));} private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private String first(String s){return s.trim().isEmpty()?"there":s.trim().split("\\s+")[0];} private String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());} private String now(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX",Locale.US).format(new Date());} private String format(long ms){long s=Math.max(0,ms)/1000;return String.format(Locale.US,"%02d:%02d",s/60,s%60);} private String strip(String s){return s.replaceAll("<[^>]*>","").replace("&nbsp;"," ");} private Object emptyNull(EditText input){String s=input.getText().toString().trim();return s.isEmpty()?JSONObject.NULL:s;} private double number(EditText input,double fallback){try{return Double.parseDouble(input.getText().toString().trim());}catch(Exception e){return fallback;}}
    private JSONObject obj(Object... values){JSONObject o=new JSONObject();try{for(int i=0;i<values.length;i+=2)o.put(String.valueOf(values[i]),values[i+1]);}catch(Exception ignored){}return o;}
}
